version: '3.8'

services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${PSQLUSER}
      POSTGRES_PASSWORD: ${PSQLPASSWORD}
      POSTGRES_DB: ${PSQLDB}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 20



